FROM node:22-alpine3.18

# Set the working directory
WORKDIR /app

# Copy package.json files
COPY server/clinic_service/package*.json ./server/clinic_service/
COPY shared/mqtt/package*.json ./shared/mqtt/

# Combine install commands and clean cache
RUN cd ./server/clinic_service && \
    npm install && \
    npm cache clean --force && \
    npm install -g nodemon

# Copy source code
COPY server/clinic_service ./server/clinic_service
COPY shared/mqtt ./shared/mqtt

# Expose the port
EXPOSE 3300

# Set environment variable
ENV NODE_ENV=development

# Start the application
CMD ["npm", "run", "dev", "--prefix", "server/clinic_service"]
